#Ethernet
print("10 BASE-T: \n2 Pairs | Cat3 min | 100m max ")
print("********************************************")
print('100 BASE-TX: \n2 Pairs | Cat5 min | 100m max ')
print("********************************************")
print('1000 BASE-T: \n4 Pairs | Cat5e min | 100m max ')
print("********************************************")
print('10G BASE-T: \n4 Pairs | Cat6 (UTP: 55m / STP : 100m) Cat6A : 100m ')
print("********************************************")
print('40G BASE-T: \n4 Pairs | Cat8 min | 30m max ')
#Fiber
print("******************************************")
print("100 BASE-FX: \nMMF Half Duplex: 400m / Full Duplex: 2km")
print("******************************************")
print("100 BASE-SX: \nMMF 300m")
print("******************************************")
print("1000 BASE-SX: \nMMF 220m to 550m")
print("******************************************")
print("1000 BASE-LX: \nMMF: 550m / SMF: 5km")
print("******************************************")
print("10G BASE-SR: \nMMF 26m to 400m")
print("******************************************")
print("10G BASE-LR: \nSMF 10km")
print("******************************************")
